/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;


import Tool.KoneksiDB;
import java.sql.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author User
 */
public class FrMenu extends javax.swing.JFrame {

    KoneksiDB getCnn = new KoneksiDB();
    Connection _Cnn;
    String viduser, vpass, vlevuser;
    
    public FrMenu() {
        initComponents();
        panelLogin.setEnabled(true);
        panelKiri.setEnabled(false);
        panelDekstop.setEnabled(false);
        mnFile.setEnabled(false);
        mnMaster.setEnabled(false);
        mnMahasiswa.setEnabled(false);
        btnCetak.setEnabled(false);
        btnJurusan.setEnabled(false);
        btnMhs.setEnabled(false);
        btnProdi.setEnabled(false);
        txtUser.requestFocus(); 
        this.setExtendedState(FrMenu.MAXIMIZED_BOTH);
    }
    
    private void aksiLogin(){
        viduser = txtUser.getText();
        vpass = txtPassword.getText();
        try{
            _Cnn = null;
            _Cnn = getCnn.getConnection();
            String sql = "SELECT * from tbuser where id_user='"+viduser+"' and " + "pass='"+vpass+"' ";
            Statement stat = (Statement) _Cnn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            if(res.first()){
                panelLogin.setVisible(false);
                panelKiri.setEnabled(true);
                panelDekstop.setEnabled(true);
                mnFile.setEnabled(true);
                mnMaster.setEnabled(true);
                mnMahasiswa.setEnabled(true);
                btnCetak.setEnabled(true);
                btnJurusan.setEnabled(true);
                btnMhs.setEnabled(true);
                btnProdi.setEnabled(true);
            }else {
                JOptionPane.showMessageDialog(this, "ID. User dan Password salah !", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error method aksiLogin() : "+ex,
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JDesktopPane();
        panelKiri = new Tool.PanelCool1();
        btnMhs = new Tool.botton();
        btnProdi = new Tool.botton();
        btnExit = new Tool.botton();
        btnCetak = new Tool.botton();
        btnJurusan = new Tool.botton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelDekstop = new Tool.PanelBackground();
        panelLogin = new Tool.PanelCool();
        label3 = new Tool.Label();
        label4 = new Tool.Label();
        jLabel4 = new javax.swing.JLabel();
        panelCool12 = new Tool.PanelCool1();
        btnLogin = new Tool.botton();
        btnKeluar = new Tool.botton();
        label1 = new Tool.Label();
        label2 = new Tool.Label();
        txtUser = new Tool.TextField();
        txtPassword = new Tool.Password();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnUser = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnMaster = new javax.swing.JMenu();
        mnJurusan = new javax.swing.JMenuItem();
        MnProdi = new javax.swing.JMenuItem();
        mnTa = new javax.swing.JMenuItem();
        mnMahasiswa = new javax.swing.JMenu();
        mnInputMahasiswa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMhs.setForeground(new java.awt.Color(255, 255, 255));
        btnMhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/3 - Mahasiswa.png"))); // NOI18N
        btnMhs.setText("Data Mahasiswa");
        btnMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMhsActionPerformed(evt);
            }
        });

        btnProdi.setForeground(new java.awt.Color(255, 255, 255));
        btnProdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dd.png"))); // NOI18N
        btnProdi.setText("Data Prodi   ");
        btnProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdiActionPerformed(evt);
            }
        });

        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/print2.png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnJurusan.setForeground(new java.awt.Color(255, 255, 255));
        btnJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dd.png"))); // NOI18N
        btnJurusan.setText("Data Jurusan");
        btnJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurusanActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-big.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AKADEMI KOMUNITAS");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NEGERI KAJEN");

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJurusan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMhs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        panelLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label3.setText("FORM LOGIN");
        label3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        label4.setText("Silahkan masukan ID. User dan Password anda !");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-medium.png"))); // NOI18N

        panelCool12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistem Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/0 - login.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/0 - login batal.png"))); // NOI18N
        btnKeluar.setText("Batal");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("ID. User");
        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Password");
        label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });

        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelCool12Layout = new javax.swing.GroupLayout(panelCool12);
        panelCool12.setLayout(panelCool12Layout);
        panelCool12Layout.setHorizontalGroup(
            panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCool12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCool12Layout.createSequentialGroup()
                        .addGap(0, 132, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCool12Layout.createSequentialGroup()
                        .addGroup(panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelCool12Layout.setVerticalGroup(
            panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCool12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCool12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelCool12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCool12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDekstop.add(panelLogin);
        panelLogin.setBounds(130, 220, 360, 230);

        jpMenu.setLayer(panelKiri, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMenu.setLayer(panelDekstop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addComponent(panelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDekstop, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDekstop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(java.awt.SystemColor.inactiveCaption);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnFile.setBackground(java.awt.SystemColor.inactiveCaption);
        mnFile.setText("Sistem");
        mnFile.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        mnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1 - user.png"))); // NOI18N
        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        mnFile.add(mnUser);

        mnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnFile.add(mnKeluar);
        mnFile.add(jSeparator1);

        jMenuBar1.add(mnFile);

        mnMaster.setBackground(java.awt.SystemColor.inactiveCaption);
        mnMaster.setText("Master");
        mnMaster.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        mnJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2 - master small.png"))); // NOI18N
        mnJurusan.setText("Master Jurusan");
        mnJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJurusanActionPerformed(evt);
            }
        });
        mnMaster.add(mnJurusan);

        MnProdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2 - master small.png"))); // NOI18N
        MnProdi.setText("Master Program Studi");
        MnProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnProdiActionPerformed(evt);
            }
        });
        mnMaster.add(MnProdi);

        mnTa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2 - master small.png"))); // NOI18N
        mnTa.setText("Master Tahun Ajaran");
        mnTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTaActionPerformed(evt);
            }
        });
        mnMaster.add(mnTa);

        jMenuBar1.add(mnMaster);

        mnMahasiswa.setBackground(java.awt.SystemColor.inactiveCaption);
        mnMahasiswa.setText("Mahasiswa");
        mnMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        mnInputMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/3 - mahasiswa small.png"))); // NOI18N
        mnInputMahasiswa.setText("Data Mahasiswa");
        mnInputMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInputMahasiswaActionPerformed(evt);
            }
        });
        mnMahasiswa.add(mnInputMahasiswa);

        jMenuBar1.add(mnMahasiswa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnInputMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInputMahasiswaActionPerformed
        IfrMahasiswa internalMhs;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalMhs = new IfrMahasiswa();
        internalMhs.setVisible(true);
        try{
            internalMhs.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalMhs);
    }//GEN-LAST:event_mnInputMahasiswaActionPerformed

    private void mnJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJurusanActionPerformed
        IfrJurusan internalJur;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalJur = new IfrJurusan();
        internalJur.setVisible(true);
        try{
            internalJur.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalJur);
    }//GEN-LAST:event_mnJurusanActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this,"Apakah anda akan keluar dari aplikasi ? ", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(jawab==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        IfrUser internalUser;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalUser = new IfrUser();
        internalUser.setVisible(true);
        try{
            internalUser.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalUser);
    }//GEN-LAST:event_mnUserActionPerformed

    private void btnMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMhsActionPerformed
        IfrMahasiswa internalMhs;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalMhs = new IfrMahasiswa();
        internalMhs.setVisible(true);
        try{
            internalMhs.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalMhs);
    }//GEN-LAST:event_btnMhsActionPerformed

    private void btnProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdiActionPerformed
        IfrProdi internalProdi;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalProdi = new IfrProdi();
        internalProdi.setVisible(true);
        try{
            internalProdi.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalProdi);
    }//GEN-LAST:event_btnProdiActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        Laporan internalLap;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalLap = new Laporan();
        internalLap.setVisible(true);
        try{
            internalLap.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalLap);
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this,"Apakah anda akan keluar dari aplikasi ? ", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(jawab==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void MnProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnProdiActionPerformed
        IfrProdi internalProdi;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalProdi = new IfrProdi();
        internalProdi.setVisible(true);
        try{
            internalProdi.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalProdi);
    }//GEN-LAST:event_MnProdiActionPerformed

    private void mnTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTaActionPerformed
        IfrThAkademik internalProdi;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalProdi = new IfrThAkademik();
        internalProdi.setVisible(true);
        try{
            internalProdi.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalProdi);
    }//GEN-LAST:event_mnTaActionPerformed

    private void btnJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurusanActionPerformed
        IfrJurusan internalJurusan;
        
        panelDekstop.removeAll();
        panelDekstop.repaint();
        internalJurusan = new IfrJurusan();
        internalJurusan.setVisible(true);
        try{
            internalJurusan.setMaximum(true);
            
        }catch(Exception e) {
            
        }
            panelDekstop.add(internalJurusan);
    }//GEN-LAST:event_btnJurusanActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
        btnLogin.doClick();
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
        txtPassword.requestFocus();
    }//GEN-LAST:event_txtUserKeyPressed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(txtUser.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Username harus diisi !","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }else if(txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Password harus diisi !","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }else if(txtUser.getText().equals("") && txtPassword.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Username dan Password harus diisi !","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }else{
            aksiLogin();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try
        {
            com.jtattoo.plaf.graphite.GraphiteLookAndFeel.setTheme("Default", "Java Swing", "");
            UIManager.setLookAndFeel("com.jtatto.plaf.graphite.GraphiteLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new FrMenu());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | UnsupportedLookAndFeelException e){
        }
        
       new FrMenu().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnProdi;
    private Tool.botton btnCetak;
    private Tool.botton btnExit;
    private Tool.botton btnJurusan;
    private Tool.botton btnKeluar;
    private Tool.botton btnLogin;
    private Tool.botton btnMhs;
    private Tool.botton btnProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jpMenu;
    private Tool.Label label1;
    private Tool.Label label2;
    private Tool.Label label3;
    private Tool.Label label4;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnInputMahasiswa;
    private javax.swing.JMenuItem mnJurusan;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenu mnMahasiswa;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenuItem mnTa;
    private javax.swing.JMenuItem mnUser;
    private Tool.PanelCool1 panelCool12;
    private Tool.PanelBackground panelDekstop;
    private Tool.PanelCool1 panelKiri;
    private Tool.PanelCool panelLogin;
    private Tool.Password txtPassword;
    private Tool.TextField txtUser;
    // End of variables declaration//GEN-END:variables
}
